import { Inter } from 'next/font/google'
import './main.css'
import Header from '@/components/NavBar/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="es">
      <body className={inter.className} id='body'>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
