import { Inter } from 'next/font/google'
import './main.css'
import Header from '@/components/NavBar/Header'
import { DeviceProvider } from '@/hooks/useContextMobile'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="es">
      <body className={inter.className} id="body">
        <DeviceProvider>
          <Header></Header>
          {children}
        </DeviceProvider>
      </body>
    </html>
  )
}
